# Generated by Django 4.0.6 on 2022-07-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='train',
            options={'verbose_name': 'Тренировка', 'verbose_name_plural': 'Тренировки'},
        ),
        migrations.AlterField(
            model_name='train',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='train',
            name='exercises',
            field=models.CharField(choices=[('E', 'Euro'), ('R', 'Rubles'), ('D', 'Dollars')], max_length=30, verbose_name='Тренировка'),
        ),
    ]
